### ISSUE TITLE
Problem with import root_numpy

### ISSUE THREAD

**Issue by vlisovsk** [scikit-hep/root_numpy#315]
Hello, I have the ROOT 5.34/34 installed some time ago from Homebrew. Now I need to install the root_numpy. I do it via 
`pip install root_numpy`
Then I try to import root_numpy in python and get this error:

>>> import root_numpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/root/5.34.34_1/lib/root/ROOT.py", line 352, in _importhook
    return _orig_ihook( name, *args, **kwds )
  File "/usr/local/lib/python2.7/site-packages/root_numpy/__init__.py", line 51, in <module>
    from ._tree import (
  File "/usr/local/Cellar/root/5.34.34_1/lib/root/ROOT.py", line 352, in _importhook
    return _orig_ihook( name, *args, **kwds )
  File "/usr/local/lib/python2.7/site-packages/root_numpy/_tree.py", line 6, in <module>
    from . import _librootnumpy
  File "/usr/local/Cellar/root/5.34.34_1/lib/root/ROOT.py", line 352, in _importhook
    return _orig_ihook( name, *args, **kwds )
  File "root_numpy/src/setup.pxi", line 5, in init _librootnumpy (root_numpy/src/_librootnumpy.cpp:5)
  File "__init__.pxd", line 989, in numpy.import_array (root_numpy/src/_librootnumpy.cpp:989)
ImportError: numpy.core.multiarray failed to import

At the same time, `import ROOT` works fine.
I checked that numpy is latest version 1.12.1 and even reinstalled it again, `import numpy` works fine.
Python has version 2.7.11.
Does anyone has an idea how to solve this issue?

**Comment by kratsg** [comment]
Please update your numpy installation:

```
pip install --upgrade numpy
```

Your numpy version is too old and does not contain the `numpy.core.multiarray` library.

@ndawe - we should probably add a min-version requirement?

**Comment by vlisovsk** [comment]
When I do `pip install --upgrade numpy`, it says
>> Requirement already up-to-date: numpy in /usr/local/lib/python2.7/site-packages

**Comment by kratsg** [comment]
Try:

```pip uninstall numpy root_numpy```

and then

```pip install --upgrade --ignore-installed --no-cache-dir numpy root_numpy```

**Comment by vlisovsk** [comment]
Thanks a lot, it seems this solved the issue!

**Comment by ndawe** [comment]
Thanks @kratsg! Fast response as usual...
