### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by malbergo** [scikit-hep/root_numpy#358]
I am failing to import root_numpy after installation via pip or source code.

I have checked the following paths: 

- $ROOTSYS is root5.34, 
- in python (2.7), import ROOT imports this same root 5.34
- my $PYTHONPATH includes the same root 5.34
- my numpy version is 1.14.0

When I install from source, I get : 
```
python setup.py install --user
running install

                 _
 _ __ ___   ___ | |_     _ __  _   _ _ __ ___  _ __  _   _
| '__/ _ \ / _ \| __|   | '_ \| | | | '_ ` _ \| '_ \| | | |
| | | (_) | (_) | |_    | | | | |_| | | | | | | |_) | |_| |
|_|  \___/ \___/ \__|___|_| |_|\__,_|_| |_| |_| .__/ \__, |  4.7.3.dev0
                   |_____|                    |_|    |___/

5.34/36
writing 'root_numpy/config.json'
running build
running build_py
copying root_numpy/config.json -> build/lib.linux-x86_64-2.7/root_numpy
running build_ext
running install_lib
creating /home/chris/.local/lib/python2.7/site-packages/root_numpy
creating /home/chris/.local/lib/python2.7/site-packages/root_numpy/tests
copying build/lib.linux-x86_64-2.7/root_numpy/tests/test_array.py -> /home/chris/.local/lib/python2.7/site-packages/root_numpy/tests
copying build/lib.linux-x86_64-2.7/root_numpy/tests/__init__.py -> /home/chris/.local/lib/python2.7/site-packages/root_numpy/tests
copying build/lib.linux-x86_64-2.7/root_numpy/tests/test_hist.py -> /home/chris/.local/lib/python2.7/site-packages/root_numpy/tests
copying build/lib.linux-x86_64-2.7/root_numpy/tests/test_sample.py -> /home/chris/.local/lib/python2.7/site-packages/root_numpy/tests
copying build/lib.linux-x86_64-2.7/root_numpy/tests/test_utils.py -> /home/chris/.local/lib/python2.7/site-packages/root_numpy/tests
copying build/lib.linux-x86_64-2.7/root_numpy/tests/test_evaluate.py -> /home/chris/.local/lib/python2.7/site-packages/root_numpy/tests
copying build/lib.linux-x86_64-2.7/root_numpy/tests/test_tree.py -> /home/chris/.local/lib/python2.7/site-packages/root_numpy/tests
copying build/lib.linux-x86_64-2.7/root_numpy/_warnings.py -> /home/chris/.local/lib/python2.7/site-packages/root_numpy
creating /home/chris/.local/lib/python2.7/site-packages/root_numpy/tmva
copying build/lib.linux-x86_64-2.7/root_numpy/tmva/_libtmvanumpy.so -> /home/chris/.local/lib/python2.7/site-packages/root_numpy/tmva
copying build/lib.linux-x86_64-2.7/root_numpy/tmva/__init__.py -> /home/chris/.local/lib/python2.7/site-packages/root_numpy/tmva
copying build/lib.linux-x86_64-2.7/root_numpy/tmva/_evaluate.py -> /home/chris/.local/lib/python2.7/site-packages/root_numpy/tmva
copying build/lib.linux-x86_64-2.7/root_numpy/tmva/_data.py -> /home/chris/.local/lib/python2.7/site-packages/root_numpy/tmva
copying build/lib.linux-x86_64-2.7/root_numpy/tmva/tests.py -> /home/chris/.local/lib/python2.7/site-packages/root_numpy/tmva
creating /home/chris/.local/lib/python2.7/site-packages/root_numpy/testdata
copying build/lib.linux-x86_64-2.7/root_numpy/testdata/test.root -> /home/chris/.local/lib/python2.7/site-packages/root_numpy/testdata
copying build/lib.linux-x86_64-2.7/root_numpy/testdata/object1.root -> /home/chris/.local/lib/python2.7/site-packages/root_numpy/testdata
copying build/lib.linux-x86_64-2.7/root_numpy/testdata/single1.root -> /home/chris/.local/lib/python2.7/site-packages/root_numpy/testdata
copying build/lib.linux-x86_64-2.7/root_numpy/testdata/trees.root -> /home/chris/.local/lib/python2.7/site-packages/root_numpy/testdata
copying build/lib.linux-x86_64-2.7/root_numpy/testdata/vary2.root -> /home/chris/.local/lib/python2.7/site-packages/root_numpy/testdata
copying build/lib.linux-x86_64-2.7/root_numpy/testdata/string.root -> /home/chris/.local/lib/python2.7/site-packages/root_numpy/testdata
copying build/lib.linux-x86_64-2.7/root_numpy/testdata/object2.root -> /home/chris/.local/lib/python2.7/site-packages/root_numpy/testdata
copying build/lib.linux-x86_64-2.7/root_numpy/testdata/__init__.py -> /home/chris/.local/lib/python2.7/site-packages/root_numpy/testdata
copying build/lib.linux-x86_64-2.7/root_numpy/testdata/fixed2.root -> /home/chris/.local/lib/python2.7/site-packages/root_numpy/testdata
copying build/lib.linux-x86_64-2.7/root_numpy/testdata/vector.root -> /home/chris/.local/lib/python2.7/site-packages/root_numpy/testdata
copying build/lib.linux-x86_64-2.7/root_numpy/testdata/ntuple.root -> /home/chris/.local/lib/python2.7/site-packages/root_numpy/testdata
copying build/lib.linux-x86_64-2.7/root_numpy/testdata/single2.root -> /home/chris/.local/lib/python2.7/site-packages/root_numpy/testdata
copying build/lib.linux-x86_64-2.7/root_numpy/testdata/fixed1.root -> /home/chris/.local/lib/python2.7/site-packages/root_numpy/testdata
copying build/lib.linux-x86_64-2.7/root_numpy/testdata/directories.root -> /home/chris/.local/lib/python2.7/site-packages/root_numpy/testdata
copying build/lib.linux-x86_64-2.7/root_numpy/testdata/vary1.root -> /home/chris/.local/lib/python2.7/site-packages/root_numpy/testdata
copying build/lib.linux-x86_64-2.7/root_numpy/testdata/struct.root -> /home/chris/.local/lib/python2.7/site-packages/root_numpy/testdata
copying build/lib.linux-x86_64-2.7/root_numpy/_graph.py -> /home/chris/.local/lib/python2.7/site-packages/root_numpy
copying build/lib.linux-x86_64-2.7/root_numpy/config.json -> /home/chris/.local/lib/python2.7/site-packages/root_numpy
copying build/lib.linux-x86_64-2.7/root_numpy/_hist.py -> /home/chris/.local/lib/python2.7/site-packages/root_numpy
copying build/lib.linux-x86_64-2.7/root_numpy/__init__.py -> /home/chris/.local/lib/python2.7/site-packages/root_numpy
copying build/lib.linux-x86_64-2.7/root_numpy/_evaluate.py -> /home/chris/.local/lib/python2.7/site-packages/root_numpy
copying build/lib.linux-x86_64-2.7/root_numpy/_librootnumpy.so -> /home/chris/.local/lib/python2.7/site-packages/root_numpy
copying build/lib.linux-x86_64-2.7/root_numpy/_utils.py -> /home/chris/.local/lib/python2.7/site-packages/root_numpy
copying build/lib.linux-x86_64-2.7/root_numpy/_sample.py -> /home/chris/.local/lib/python2.7/site-packages/root_numpy
copying build/lib.linux-x86_64-2.7/root_numpy/_array.py -> /home/chris/.local/lib/python2.7/site-packages/root_numpy
creating /home/chris/.local/lib/python2.7/site-packages/root_numpy/extern
copying build/lib.linux-x86_64-2.7/root_numpy/extern/six.py -> /home/chris/.local/lib/python2.7/site-packages/root_numpy/extern
copying build/lib.linux-x86_64-2.7/root_numpy/extern/ordereddict.py -> /home/chris/.local/lib/python2.7/site-packages/root_numpy/extern
copying build/lib.linux-x86_64-2.7/root_numpy/extern/__init__.py -> /home/chris/.local/lib/python2.7/site-packages/root_numpy/extern
copying build/lib.linux-x86_64-2.7/root_numpy/_tree.py -> /home/chris/.local/lib/python2.7/site-packages/root_numpy
copying build/lib.linux-x86_64-2.7/root_numpy/info.py -> /home/chris/.local/lib/python2.7/site-packages/root_numpy
copying build/lib.linux-x86_64-2.7/root_numpy/_matrix.py -> /home/chris/.local/lib/python2.7/site-packages/root_numpy
copying build/lib.linux-x86_64-2.7/root_numpy/setup_utils.py -> /home/chris/.local/lib/python2.7/site-packages/root_numpy
byte-compiling /home/chris/.local/lib/python2.7/site-packages/root_numpy/tests/test_array.py to test_array.pyc
byte-compiling /home/chris/.local/lib/python2.7/site-packages/root_numpy/tests/__init__.py to __init__.pyc
byte-compiling /home/chris/.local/lib/python2.7/site-packages/root_numpy/tests/test_hist.py to test_hist.pyc
byte-compiling /home/chris/.local/lib/python2.7/site-packages/root_numpy/tests/test_sample.py to test_sample.pyc
byte-compiling /home/chris/.local/lib/python2.7/site-packages/root_numpy/tests/test_utils.py to test_utils.pyc
byte-compiling /home/chris/.local/lib/python2.7/site-packages/root_numpy/tests/test_evaluate.py to test_evaluate.pyc
byte-compiling /home/chris/.local/lib/python2.7/site-packages/root_numpy/tests/test_tree.py to test_tree.pyc
byte-compiling /home/chris/.local/lib/python2.7/site-packages/root_numpy/_warnings.py to _warnings.pyc
byte-compiling /home/chris/.local/lib/python2.7/site-packages/root_numpy/tmva/__init__.py to __init__.pyc
byte-compiling /home/chris/.local/lib/python2.7/site-packages/root_numpy/tmva/_evaluate.py to _evaluate.pyc
byte-compiling /home/chris/.local/lib/python2.7/site-packages/root_numpy/tmva/_data.py to _data.pyc
byte-compiling /home/chris/.local/lib/python2.7/site-packages/root_numpy/tmva/tests.py to tests.pyc
byte-compiling /home/chris/.local/lib/python2.7/site-packages/root_numpy/testdata/__init__.py to __init__.pyc
byte-compiling /home/chris/.local/lib/python2.7/site-packages/root_numpy/_graph.py to _graph.pyc
byte-compiling /home/chris/.local/lib/python2.7/site-packages/root_numpy/_hist.py to _hist.pyc
byte-compiling /home/chris/.local/lib/python2.7/site-packages/root_numpy/__init__.py to __init__.pyc
byte-compiling /home/chris/.local/lib/python2.7/site-packages/root_numpy/_evaluate.py to _evaluate.pyc
byte-compiling /home/chris/.local/lib/python2.7/site-packages/root_numpy/_utils.py to _utils.pyc
byte-compiling /home/chris/.local/lib/python2.7/site-packages/root_numpy/_sample.py to _sample.pyc
byte-compiling /home/chris/.local/lib/python2.7/site-packages/root_numpy/_array.py to _array.pyc
byte-compiling /home/chris/.local/lib/python2.7/site-packages/root_numpy/extern/six.py to six.pyc
byte-compiling /home/chris/.local/lib/python2.7/site-packages/root_numpy/extern/ordereddict.py to ordereddict.pyc
byte-compiling /home/chris/.local/lib/python2.7/site-packages/root_numpy/extern/__init__.py to __init__.pyc
byte-compiling /home/chris/.local/lib/python2.7/site-packages/root_numpy/_tree.py to _tree.pyc
byte-compiling /home/chris/.local/lib/python2.7/site-packages/root_numpy/info.py to info.pyc
byte-compiling /home/chris/.local/lib/python2.7/site-packages/root_numpy/_matrix.py to _matrix.pyc
byte-compiling /home/chris/.local/lib/python2.7/site-packages/root_numpy/setup_utils.py to setup_utils.pyc
running install_egg_info
running egg_info
writing requirements to root_numpy.egg-info/requires.txt
writing root_numpy.egg-info/PKG-INFO
writing top-level names to root_numpy.egg-info/top_level.txt
writing dependency_links to root_numpy.egg-info/dependency_links.txt
reading manifest file 'root_numpy.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.pyo' found anywhere in distribution
warning: no previously-included files matching '*.pyd' found anywhere in distribution
writing manifest file 'root_numpy.egg-info/SOURCES.txt'
Copying root_numpy.egg-info to /home/chris/.local/lib/python2.7/site-packages/root_numpy-4.7.3.dev0-py2.7.egg-info
running install_scripts
removing 'root_numpy/config.json'

```

When I then import from python I get:

```
python
Python 2.7.14 |Anaconda custom (64-bit)| (default, Oct 16 2017, 17:29:19) 
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import root_numpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "root_numpy/__init__.py", line 51, in <module>
    from ._tree import (
  File "/usr/local/root5/lib/ROOT.py", line 352, in _importhook
    return _orig_ihook( name, *args, **kwds )
  File "root_numpy/_tree.py", line 6, in <module>
    from . import _librootnumpy
ImportError: cannot import name _librootnumpy


```

- After fully uninstalling and reinstalling via pip, I get the following import error.

`ImportError: /home/chris/.local/lib/python2.7/site-packages/root_numpy/_librootnumpy.so: undefined symbol: _ZN10TClassEdit14ResolveTypedefB5cxx11EPKcb`

Any ideas on what might be going wrong?

Thanks for any help you may be able to offer.

Best,
Michael

**Comment by kratsg** [comment]
Is there a reason you're using root5 (not really supported anymore). In any case, most of what you have sounds related to #277. Mainly having "multiples" of binaries installed... but is there a reason you need ROOT5?

**Comment by malbergo** [comment]
Thanks for your response. I'm using ROOT5 because it seems to work the best with Delphes (fast detector simulator I'm using). Yet, I can try and rebuild with ROOT6. The trouble is I have been having compatibility issues between Pythia and Delphes with ROOT6. I'll give it a look, though, and a look at #277

**Comment by malbergo** [comment]
Using, ROOT 6.08, I get the same error. Should I try removing the other binaries?

Michael

**Comment by kratsg** [comment]
Can you make sure you're setting the paths correctly? In particular, you might have problems with numpy+root+root_numpy and the gcc they're all using. Are you sure they're all using the right compiler, etc? You might need to build from scratch. Is this on a Mac or Linux?

**Comment by malbergo** [comment]
Which paths would be the correct ones here? I am using ubuntu 16.04.

**Comment by kratsg** [comment]
Like I mentioned in the issue, check what `root-config` tells you, and check what numpy is built against. Most likely, numpy and ROOT are built against different compilers, so root-numpy has a problem.

**Comment by malbergo** [comment]
Right, thanks.

My `root-config --config` output says:

`BLAS_blas_LIBRARY=/usr/lib/libblas.so JPEG_INCLUDE_DIR=/usr/include JPEG_LIBRARY=/usr/lib/x86_64-linux-gnu/libjpeg.so LIBXML2_INCLUDE_DIR=/usr/include/libxml2 LIBXML2_LIBRARIES=/usr/lib/x86_64-linux-gnu/libxml2.so OPENGL_INCLUDE_DIR=/usr/include OPENGL_gl_LIBRARY=/usr/lib/x86_64-linux-gnu/libGL.so OPENGL_glu_LIBRARY=/usr/lib/x86_64-linux-gnu/libGLU.so OPENSSL_CRYPTO_LIBRARY=/usr/lib/x86_64-linux-gnu/libcrypto.so OPENSSL_INCLUDE_DIR=/usr/include OPENSSL_SSL_LIBRARY=/usr/lib/x86_64-linux-gnu/libssl.so PC_LIBXML_INCLUDEDIR=/usr/include PC_LIBXML_INCLUDE_DIRS=/usr/include/libxml2 PC_LIBXML_LIBRARIES=xml2 PC_LIBXML_STATIC_INCLUDE_DIRS=/usr/include/libxml2 PNG_LIBRARY=/usr/lib/x86_64-linux-gnu/libpng.so PNG_LIBRARY_RELEASE=/usr/lib/x86_64-linux-gnu/libpng.so PNG_PNG_INCLUDE_DIR=/usr/include PYTHIA8_INCLUDE_DIR=/opt/pythia8/include PYTHIA8_LIBRARY=/opt/pythia8/lib/libpythia8.so PYTHON_INCLUDE_DIR=/usr/include/python2.7 PYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython2.7.so PYTHON_LIBRARY_RELEASE=/usr/lib/x86_64-linux-gnu/libpython2.7.so TIFF_INCLUDE_DIR=/usr/include/x86_64-linux-gnu TIFF_LIBRARY=/usr/lib/x86_64-linux-gnu/libtiff.so TIFF_LIBRARY_RELEASE=/usr/lib/x86_64-linux-gnu/libtiff.so X11_ICE_INCLUDE_PATH=/usr/include X11_SM_INCLUDE_PATH=/usr/include X11_X11_INCLUDE_PATH=/usr/include X11_XShm_INCLUDE_PATH=/usr/include X11_XSync_INCLUDE_PATH=/usr/include X11_Xaccessstr_INCLUDE_PATH=/usr/include X11_Xau_INCLUDE_PATH=/usr/include X11_Xdamage_INCLUDE_PATH=/usr/include X11_Xdmcp_INCLUDE_PATH=/usr/include X11_Xfixes_INCLUDE_PATH=/usr/include X11_Xft_INCLUDE_PATH=/usr/include X11_Xkb_INCLUDE_PATH=/usr/include X11_Xkblib_INCLUDE_PATH=/usr/include X11_Xlib_INCLUDE_PATH=/usr/include X11_Xmu_INCLUDE_PATH=/usr/include X11_Xpm_INCLUDE_PATH=/usr/include X11_Xrender_INCLUDE_PATH=/usr/include X11_Xscreensaver_INCLUDE_PATH=/usr/include X11_Xshape_INCLUDE_PATH=/usr/include X11_Xt_INCLUDE_PATH=/usr/include X11_Xutil_INCLUDE_PATH=/usr/include X11_dpms_INCLUDE_PATH=/usr/include X11_xf86vmode_INCLUDE_PATH=/usr/include XROOTD_INCLUDE_DIR=/opt/xrootd/include/xrootd XROOTD_XrdCl_LIBRARY=/opt/xrootd/lib/libXrdCl.so XROOTD_XrdClient_LIBRARY=/opt/xrootd/lib/libXrdClient.so XROOTD_XrdUtils_LIBRARY=/opt/xrootd/lib/libXrdUtils.so ZLIB_INCLUDE_DIR=/usr/include ZLIB_LIBRARY=/usr/lib/x86_64-linux-gnu/libz.so ZLIB_LIBRARY_RELEASE=/usr/lib/x86_64-linux-gnu/libz.so
` 

And my `root-config --arch` is linuxx8664gcc

and my `gcc --version` is `gcc (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609
`

I installed numpy with anaconda, presumably with the same compiler. Is there a way to check that?

**Comment by eduardo-rodrigues** [comment]
@malbergo and @kratsg, should this not be closed at this point? I hope you got it working!
