### ISSUE TITLE
root_numpy.tmva.tests.test_tmva_multiclass fails on my machine

### ISSUE THREAD

**Issue by jheuel** [scikit-hep/root_numpy#374]
The predictions in this test only add up to 0.99999994 in each entry.
```
FAIL: root_numpy.tmva.tests.test_tmva_multiclass
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/jheuel/repositories/root_numpy/root_numpy/tmva/tests.py", line 254, in test_tmva_multiclass
    np.ones(y_decision.shape[0]))
  File "/usr/lib/python3.7/site-packages/numpy/testing/_private/utils.py", line 865, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/usr/lib/python3.7/site-packages/numpy/testing/_private/utils.py", line 789, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

(mismatch 1.5999999999999943%)
 x: array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,...
 y: array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,...

----------------------------------------------------------------------
```

**Comment by eduardo-rodrigues** [comment]
I'm closing this issue at this point since the most current version of the packages sees no such test failure. Also, the package is being deprecated in benefit of the `uproot` package. Maybe you are already using it?
